---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: exporter
  ports:
    - name: http
      port: 9115
      targetPort: http
      protocol: TCP
